[package]
name = "Helloworldsampleenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
prost = { git = "https://github.com/mesalock-linux/prost-sgx" }
bytes = { git = "https://github.com/mesalock-linux/bytes-sgx" }
prost-types = { git = "https://github.com/mesalock-linux/prost-sgx" }

[build-dependencies]
prost-build = "*"

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk.git" }
sgx_tstd = { rev = "v1.0.9", git = "https://github.com/baidu/rust-sgx-sdk.git" }
