[package]
name = "Helloregexsampleenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "helloregexsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
regex = { path = "../../../third_party/regex" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../../../sgx_types" }
sgx_tstd = { path = "../../../sgx_tstd" }
