[package]
name = "Staticdatadistribution"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "staticdatadistribution"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "../../../sgx_types" }
sgx_tstd = { path = "../../../sgx_tstd" }
sgx_crypto_helper = { package="sgx_tcrypto_helper", path = "../../../sgx_tcrypto_helper"}

[target.'cfg(target_env = "sgx")'.dependencies]
sgx_crypto_helper = { package="sgx_tcrypto_helper", path = "../../../sgx_tcrypto_helper" }

[dependencies]
serde_json = { path = "../../../third_party/serde-rs/json" }
